### ISSUE TITLE
No available formula with the name "/automake-1.15"

### ISSUE THREAD

**Issue by uhthomas** [Amar1729/homebrew-libguestfs#9]
```sh
❯ brew tap amar1729/libguestfs
❯ brew install libguestfs
Warning: No available formula with the name "/automake-1.15" (dependency of amar1729/libguestfs/libguestfs). Did you mean automake-1.15?
```

**Comment by Amar1729** [comment]
Yeah ... I think I may have to deprecate the formulae in this tap, as the most recent version i could build (`1.32`) is quite old at this point, and `osxfuse` isn't in homebrew anymore.

**Comment by Amar1729** [comment]
Closed w/ deprecation notice. No clue how to build this on current macOS :/
